from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def read_csv(path: Path):
    hours = []
    air = []
    wall = []
    out = []
    q_ac = []

    with path.open("r", newline="") as handle:
        reader = csv.reader(handle)
        for row in reader:
            if not row:
                continue
            hours.append(float(row[0]))
            air.append(float(row[1]))
            wall.append(float(row[2]))
            out.append(float(row[3]))
            q_ac.append(float(row[4]))

    return hours, air, wall, out, q_ac


def main():
    parser = argparse.ArgumentParser(description="Plot room dynamics from CSV data.")
    parser.add_argument("csv", type=Path, help="CSV file generated by validate_dynamics.py")
    parser.add_argument("--out", type=Path, default=None, help="Optional output PNG path")
    args = parser.parse_args()

    hours, air, wall, out, q_ac = read_csv(args.csv)

    fig, ax1 = plt.subplots(figsize=(9, 5))
    ax1.plot(hours, air, label="Air temp (C)", color="tab:blue")
    ax1.plot(hours, wall, label="Wall temp (C)", color="tab:orange", linestyle="--")
    ax1.plot(hours, out, label="Outdoor temp (C)", color="tab:green")
    ax1.set_xlabel("Hour")
    ax1.set_ylabel("Temperature (C)")
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc="upper right")

    ax2 = ax1.twinx()
    ax2.plot(hours, q_ac, label="AC power (W)", color="tab:red", alpha=0.6)
    ax2.set_ylabel("AC power (W)")

    fig.tight_layout()

    if args.out:
        fig.savefig(args.out, dpi=150)
    else:
        plt.show()


if __name__ == "__main__":
    main()
